### PR TITLE
Modify pessimistic version for YapDatabase

### PR DESCRIPTION
**Pull request by giginet**
YapDatabase 2.9.3 is already released.
However, Puree uses the older one.

To suppress the warning, I'd like to use newest.
So I modified dependencies version.

@slightair Please review it :pray:

### CODE REVIEW

**Comment by slightair** [comment]
Thanks!

Please rebase it.

**Comment by giginet** [comment]
I'd like to use YapDatabase 2.9.3 to suppress the warning.

screen shot 2017-01-05 at 14 24 21

https://github.com/yapstudios/YapDatabase/releases/tag/2.9.3

However, it is not released on CocoaPods yet 😢

**Comment by giginet** [comment]
I'm waiting for publishing latest YapDatabase onto CocoaPods.
So, I can't merge this PR 😢 

We should wait for it or refer the released tag directly.

**Comment by giginet** [comment]
YapDatabase2.9.3 have been released yesterday at long last 😂 

https://github.com/CocoaPods/Specs/commit/1a35ee8192596d960b6e4e005da7a24ba32600d3

**Comment by slightair** [comment]
Thanks 😸

**Pull request merged**
